# Generated by Django 4.1.1 on 2022-10-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
